### ISSUE TITLE
Request for openmpi implement

### ISSUE THREAD

**Issue by scott-5** [deepmd-kit-recipes/plumed-feedstock#9]
I am using deepmd-kit [v3.0.0b3](https://github.com/deepmodeling/deepmd-kit/releases/tag/v3.0.0b3) offline that requires openmpi >=4.1.6, which contains plumed with default module config (from conda-forge channel) and lammps (compatible with deepmd-kit).

However I wanna use some modules that are turned off by default in plumed. So I have to reinstall plumed in above conda env.

Then I install plumed from deepmodeling channel, which is built by this plumed-feedstock. But the problem is that plumed built from this feedstock is based on mpich implement, which seems conflict with openmpi required with deepmd-kit. The detail reports is that:
```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package deepmd-kit-3.0.0b3-cuda120py311hdc0cc46_mpi_openmpi_0 requires openmpi >=4.1.6,<5.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ deepmd-kit 3.0.0b3.*  is installable with the potential options
│  ├─ deepmd-kit 3.0.0b3 would require
│  │  └─ openmpi >=4.1.6,<5.0a0  with the potential options
│  │     ├─ openmpi 4.1.6 would require
│  │     │  └─ mpi 1.0 openmpi, which can be installed;
│  │     └─ openmpi 4.1.6 conflicts with any installable versions previously reported;
│  └─ deepmd-kit 3.0.0b3 conflicts with any installable versions previously reported;
└─ plumed 2.8.2**  is not installable because there are no viable options
   ├─ plumed 2.8.2 would require
   │  └─ mpich >=4.1.1,<5.0a0  but there are no viable options
   │     ├─ mpich 4.1.1 would require
   │     │  └─ mpi 1.0 mpich, which conflicts with any installable versions previously reported;
   │     └─ mpich [4.1.1|4.1.2|4.2.0|4.2.1|4.2.2] conflicts with any installable versions previously reported;
   └─ plumed 2.8.2 conflicts with any installable versions previously reported.
```
Therefore, if there is an openmpi implemented plumed in the deepmodeling channel, I may be able to reinstall plume with all modules in the above conda environment, and then the problem can be solved.

Thanks and look forward for your reply.

**Comment by njzjz** [comment]
The deepmodeling channel has been deprecated. No new packages will be added anymore.

**Comment by scott-5** [comment]
OK, thank you.
